Procesado de Variables sklearn 

In [1]:
%load_ext watermark
%watermark

Last updated: 2021-05-11T13:31:30.857996-05:00

Python implementation: CPython
Python version       : 3.7.6
IPython version      : 7.12.0

Compiler    : MSC v.1916 64 bit (AMD64)
OS          : Windows
Release     : 10
Machine     : AMD64
Processor   : Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
CPU cores   : 8
Architecture: 64bit



In [3]:
%matplotlib inline
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
datos = pd.read_csv("data/datos_procesamiento.csv")

In [16]:
datos.dtypes

col_inexistente1    float64
col2                float64
col3                float64
col_outliers          int64
col_outliers2       float64
col_categorica       object
col_ordinal          object
col_texto            object
objetivo              int64
dtype: object

In [30]:
from sklearn import preprocessing

In [20]:
datos.dtypes

col_inexistente1    float64
col2                float64
col3                float64
col_outliers          int64
col_outliers2       float64
col_categorica       object
col_ordinal          object
col_texto            object
objetivo              int64
dtype: object

In [22]:
#definimos las variables númericas 
# como aquellas que type float

var_numericas_df = datos.select_dtypes([int, float])
var_numericas_df.columns

Index(['col_inexistente1', 'col2', 'col3', 'col_outliers2'], dtype='object')

In [38]:
#buscamos aquellas observaciones que contengan nulos

var_numericas_df[var_numericas_df.isnull().any(axis=1)].head()

col_inexistente1  col2      col3  col_outliers2
9                NaN  53.0  2.270999       1.067230
10               NaN  99.0  1.394209       4.145716
16               NaN  50.0  0.437365      20.549474
17               NaN  73.0  0.324893       0.761684
23               NaN  85.0  3.664671       3.154153

In [33]:
# el metodo imputer en preprocesamiento de datos 
# quedó desactivado para la versión actual de sklearn
from sklearn.impute import SimpleImputer 

In [34]:
imputador = SimpleImputer(strategy='mean')

In [35]:
var_numericas_imputadas = imputador.fit_transform(var_numericas_df)

In [40]:
var_numericas_imputadas

array([[59.        , 52.        ,  2.23283208,  0.77166646],
       [31.        , 74.        ,  0.90614714,  1.06855838],
       [81.        , 28.        ,  0.62675042,  0.84639576],
       ...,
       [19.        , 53.        ,  0.73723413,  1.34525201],
       [88.        , 94.        ,  0.76008706,  1.3692463 ],
       [94.        , 56.        ,  1.2299403 ,  0.94395714]])

In [41]:
var_numericas_imputadas.shape

(1000, 4)

In [42]:

var_numericas_imputadas_df = pd.DataFrame(var_numericas_imputadas,
                                                   index=var_numericas_df.index,
                                                   columns=var_numericas_df.columns)

var_numericas_imputadas_df.head(10)


col_inexistente1  col2       col3  col_outliers2
0         59.000000  52.0   2.232832       0.771666
1         31.000000  74.0   0.906147       1.068558
2         81.000000  28.0   0.626750       0.846396
3         34.000000  16.0   0.816738       0.637381
4         32.000000  28.0   0.571131       4.540614
5         81.000000   4.0   1.618844       0.812940
6         57.000000  31.0   0.167880       1.235137
7         34.000000  20.0  20.229813       1.283176
8         37.000000  96.0   2.407978       1.298613
9         48.382743  53.0   2.270999       1.067230

In [43]:
var_numericas_imputadas_df[var_numericas_imputadas_df.isnull().any(axis=1)].shape

(0, 4)

#### Estadanrización  

La estandarización es un proceso requerido en muchos modelos de sklearn. Variable media 0 y desviasión estandar 1 

In [44]:
var_numericas_df.columns 

Index(['col_inexistente1', 'col2', 'col3', 'col_outliers2'], dtype='object')

In [45]:
var_numericas_df.mean()

col_inexistente1     48.382743
col2                 49.660000
col3                  1.466095
col_outliers2       131.193340
dtype: float64

In [46]:
var_numericas_df.std()

col_inexistente1      27.987174
col2                  28.272668
col3                   1.732358
col_outliers2       3401.164776
dtype: float64

Para skl el escalador más sencillo es standarscaler

In [47]:
escalador = preprocessing.StandardScaler()
var_numericas_imputadas_escalado_standar = escalador.fit_transform(var_numericas_imputadas)

In [48]:
escalador.mean_

array([ 48.38274336,  49.66      ,   1.46609489, 131.19333968])

In [53]:
var_numericas_imputadas_escalado_standar.mean(axis=0)

array([-5.86197757e-17,  1.26121336e-16, -3.99680289e-17, -3.55271368e-18])

In [55]:
var_numericas_imputadas_escalado_standar.std(axis=0)

array([1., 1., 1., 1.])

In [57]:
var_numericas_imputadas_escalado_standar[0]

array([ 0.39921733,  0.08280686,  0.44281884, -0.03836537])

Para aquellos casos en los que los datos tengan muchos valores extremos, es posible que estandarizar usando la media y la desviacion estandar no funcione bien en el modelo. Para esos casos es mejor usar unos estimadores mas robustos (menos sensibles a outliers) y emplear un RobustScaler que funciona substrayendo la mediana y escalando mediante el rango intercuartil (IQR).

In [58]:
escalador_robusto = preprocessing.RobustScaler()
var_numericas_imputadas_escalado_robusto = escalador_robusto.fit_transform(

var_numericas_imputadas)

In [59]:
var_numericas_imputadas_escalado_robusto.mean(axis=0)

array([-3.81916720e-17, -2.85106383e-02,  4.01958704e-01,  7.03130782e+01])

In [60]:
var_numericas_imputadas_escalado_robusto.std(axis=0)

array([6.33218559e-01, 6.01245275e-01, 1.38651621e+00, 1.83690817e+03])

#### Escalado en un rango especifico 

Hay casos en los que en vez de estandardizar queremos escalar los datos a un rango (generalmente [-1,1] o [0,1]). Para ello podemos usar MinMaxScaler que hace escalado minmax (obviamente) o MaxAbscaler que simplemente divide cada valor de una variable por su valor máximo (y por tanto convierte el valor maximo a 1).

In [61]:
var_numericas_imputadas.min()

-20.72774653276077

In [62]:
var_numericas_imputadas.max()

107357.85777352

In [63]:
escalador_minmax = preprocessing.MinMaxScaler()

var_numericas_imputadas_escalado_minmax = escalador_minmax.fit_transform(var_numericas_imputadas)

In [64]:
var_numericas_imputadas_escalado_minmax.max()

1.0

In [65]:
var_numericas_imputadas_escalado_minmax.min()

0.0

In [66]:
escalador_maxabs = preprocessing.MaxAbsScaler()
var_numericas_imputadas_escalado_maxabs = escalador_maxabs.fit_transform(var_numericas_imputadas)

In [67]:
var_numericas_imputadas_escalado_maxabs.max()

1.0

In [68]:
var_numericas_imputadas_escalado_maxabs.min()

-0.00019307153628649718

Existen casos en los que es necesario tener observaciones con norma unitaria, para esos casos podemos utilizar normalizer, hay que tener en cuenta tambien que normalizer normaliza casos, no variables  

In [70]:
normalizador = preprocessing.Normalizer()
var_numericas_imputadas_normal = normalizador.fit_transform(var_numericas_imputadas)

In [71]:
var_numericas_imputadas_normal[1,:]

array([0.38632582, 0.92219711, 0.01129252, 0.01331651])

In [72]:
np.linalg.norm(var_numericas_imputadas_normal[1,:])

0.9999999999999998

In [73]:
from sklearn.preprocessing import FunctionTransformer
transformer = FunctionTransformer(np.log1p)

In [74]:
col3_transformada = transformer.transform(datos[["col3"]])
col3_transformada = col3_transformada.reshape(col3_transformada.shape[0],)
sns.kdeplot(col3_transformada);

AttributeError: 'DataFrame' object has no attribute 'reshape'

In [77]:
col_numericas =  ['col_inexistente1', 'col2', 'col3', 'col_outliers', 'col_outliers2']
col_categorica = ['col_categorica']
col_texto = ['col_texto']


In [79]:
#Variables numéricas
imputador = SimpleImputer(strategy='mean')
escalador = preprocessing.StandardScaler()
var_numericas_imputadas_escalado_standard = escalador.fit_transform(
                                                imputador.fit_transform(datos[col_numericas])
                                            )
df_numerico_procesado = pd.DataFrame(var_numericas_imputadas_escalado_standard,
                                                   columns=col_numericas)

In [80]:
# Variable categorica
label_codificador_categorico = preprocessing.LabelEncoder()
categorias_codificadas = label_codificador_categorico.fit_transform(datos[col_categorica])
oh_codificador = preprocessing.OneHotEncoder(sparse=False)
categorias_oh_codificadas = oh_codificador.fit_transform(categorias_codificadas.reshape(1000,1))

df_categorico_procesado = pd.DataFrame(categorias_oh_codificadas, 
                                       columns=label_codificador_categorico.classes_)

C:\Users\carlo\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [85]:
# Texto
vectorizador_tfidf = feature_extraction.text.TfidfVectorizer()
texto_vectorizado = vectorizador_tfidf.fit_transform(datos.col_texto)
df_texto_procesado =  pd.DataFrame(texto_vectorizado.toarray(), columns=vectorizador_tfidf.get_feature_names())


datos_procesados = pd.concat([
    df_numerico_procesado,
    df_categorico_procesado,
    df_texto_procesado 
], axis=1)

# variable ordinal
label_codificador_ordinal = preprocessing.LabelEncoder()
datos_procesados['col_ordinal'] = label_codificador_ordinal.fit_transform(datos.col_ordinal)

In [84]:
from sklearn import feature_extraction

In [86]:
datos_procesados

col_inexistente1      col2      col3  col_outliers  col_outliers2  \
0            0.399217  0.082807  0.442819     -0.694600      -0.038365   
1           -0.653605  0.861333 -0.323390     -0.118466      -0.038278   
2            1.226435 -0.766494 -0.484752     -0.464146      -0.038343   
3           -0.540803 -1.191145 -0.375028     -1.129901      -0.038405   
4           -0.616004 -0.766494 -0.516874      0.777743      -0.037257   
..                ...       ...       ...           ...            ...   
995          1.376838  0.365907  0.492254      0.611304      -0.038492   
996         -0.352799 -1.615795  0.131503      0.700925      -0.037878   
997         -1.104815  0.118194 -0.420944      0.880166      -0.038197   
998          1.489641  1.569084 -0.407745      0.816152      -0.038190   
999          1.715245  0.224357 -0.136388      0.726531      -0.038315   

     elefante  gato  perro  ratón  acordarme  ...      vaca    veinte  \
0         0.0   0.0    0.0    1.0   0.000000  ...  0.000000  0.204745   
1         1.0   0.0    0.0    0.0   0.000000  ...  0.000000  0.000000   
2         0.0   0.0    0.0    1.0   0.000000  ...  0.000000  0.000000   
3         0.0   1.0    0.0    0.0   0.000000  ...  0.194272  0.000000   
4         0.0   1.0    0.0    0.0   0.000000  ...  0.000000  0.204745   
..        ...   ...    ...    ...        ...  ...       ...       ...   
995       1.0   0.0    0.0    0.0   0.000000  ...  0.000000  0.000000   
996       0.0   0.0    0.0    1.0   0.000000  ...  0.000000  0.204745   
997       1.0   0.0    0.0    0.0   0.000000  ...  0.000000  0.000000   
998       1.0   0.0    0.0    0.0   0.197887  ...  0.000000  0.000000   
999       1.0   0.0    0.0    0.0   0.000000  ...  0.000000  0.204745   

      velarte   vellori   velludo  verdad  verosímiles   viernes     vivía  \
0    0.000000  0.000000  0.000000     0.0          0.0  0.000000  0.000000   
1    0.181842  0.181842  0.181842     0.0          0.0  0.000000  0.000000   
2    0.181842  0.181842  0.181842     0.0          0.0  0.000000  0.000000   
3    0.000000  0.000000  0.000000     0.0          0.0  0.194272  0.000000   
4    0.000000  0.000000  0.000000     0.0          0.0  0.000000  0.000000   
..        ...       ...       ...     ...          ...       ...       ...   
995  0.000000  0.000000  0.000000     0.0          0.0  0.000000  0.000000   
996  0.000000  0.000000  0.000000     0.0          0.0  0.000000  0.000000   
997  0.181842  0.181842  0.181842     0.0          0.0  0.000000  0.000000   
998  0.000000  0.000000  0.000000     0.0          0.0  0.000000  0.197887   
999  0.000000  0.000000  0.000000     0.0          0.0  0.000000  0.000000   

     col_ordinal  
0              2  
1              4  
2              3  
3              1  
4              0  
..           ...  
995            3  
996            2  
997            4  
998            0  
999            4  

[1000 rows x 144 columns]

In [87]:
pd.get_dummies(datos.col_categorica).head()

elefante  gato  perro  ratón
0         0     0      0      1
1         1     0      0      0
2         0     0      0      1
3         0     1      0      0
4         0     1      0      0

## Texto 

In [88]:
from sklearn import feature_extraction

In [89]:
datos.col_texto.values[:10]

array(['Tenía en su casa una ama que pasaba de los cuarenta, y una sobrina que no llegaba a los veinte, y un mozo de campo y plaza, que así ensillaba el rocín como tomaba la podadera.',
       'El resto della concluían sayo de velarte, calzas de velludo para las fiestas con sus pantuflos de lo mismo, los días de entre semana se honraba con su vellori de lo más fino.',
       'El resto della concluían sayo de velarte, calzas de velludo para las fiestas con sus pantuflos de lo mismo, los días de entre semana se honraba con su vellori de lo más fino.',
       'Una olla de algo más vaca que carnero, salpicón las más noches, duelos y quebrantos los sábados, lentejas los viernes, algún palomino de añadidura los domingos, consumían las tres partes de su hacienda.',
       'Tenía en su casa una ama que pasaba de los cuarenta, y una sobrina que no llegaba a los veinte, y un mozo de campo y plaza, que así ensillaba el rocín como tomaba la podadera.',
       'En un lugar de la Mancha, de cuyo nom

Para convertir el texto en variables númericas, separamos por columna la palabra, con countvectorizer, devuleve binarios, sin embargo esto no refleja el valor de las frases

Una manera más sofisticada de vectorizar un texto es en vez de usar el número de apariciones, usar TF-IDF. TF-IDF se traduce como Frecuencia de Texto - Frecuencia Inversa de Documento, y es una medida que asigna pesos a cada palabra en función de su frecuencia de aparición en todos los documents.

In [92]:
vectorizador_tfidf = feature_extraction.text.TfidfVectorizer()
X = vectorizador_tfid.fit_transform(datos.col_texto)
pd.DataFrame(X.toarray(), columns=vectorizador_tfidf.get_feature_names())


NameError: name 'vectorizador_tfid' is not defined